node-build: 
  image: node:20
  stage: build
  cache:
    key: node-cache
    paths: [.source/node_modules]
  before_script:
   - cd source
  script: 
   - npm install
   - npm run build:dev
  artifacts:
    paths:
      - ./source/build
  only:
    - dev
